### ISSUE TITLE
Lu mau gua pukul?

### ISSUE THREAD

**Issue by wikankun** [MAAF72/DAA-Course#1]
Ini disubmit ke dosen ngga? Masa dosennya mau dipukul wkwk

**Comment by MAAF72** [comment]
Ya ini kan dibikin publik aja wkwkk
masa ngesort cuman 1 element wkwk ngajak bercanda namanya

**Comment by wikankun** [comment]
> Ya ini kan dibikin publik aja wkwkk
> masa ngesort cuman 1 element wkwk ngajak bercanda namanya

yaudah saya close ya issuenya wkwk
